# https://dystroy.org/bacon/config/
# https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml

[keybindings]
shift-g = "scroll-to-bottom"

[jobs.app-backend]
command = [
  "cargo",
  "run",
  "-p",
  "app",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
default_watch = false
watch = [
  "apps/app/server",
]
ignore = [
  "**/*.gen.*",
]

[jobs.app-frontend]
command = [
  "pnpm",
  "-F",
  "app",
  "build",
]
need_stdout = true
allow_warnings = true
background = false
on_change_strategy = "kill_then_restart"
default_watch = false
watch = [
  "apps/app/src",
]
ignore = [
  "**/*.gen.*",
]
