services:
  cerbos:
    image: ghcr.io/cerbos/cerbos:0.40.0
    ports:
      - "3592:3592"
  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio-user
      MINIO_ROOT_PASSWORD: minio-password
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
  createbuckets:
    image: minio/mc
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minio-user minio-password;
      /usr/bin/mc mb myminio/hyprnote-dev;
      /usr/bin/mc anonymous set public myminio/hyprnote-dev;
      exit 0;
      "
