# fly.toml app configuration file generated for hypr-server on 2025-01-01T19:42:13+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hypr-server'
primary_region = 'sjc'

[build]
dockerfile = 'Dockerfile'

[build.args]
VITE_CLERK_PUBLISHABLE_KEY = "pk_test_aW5jbHVkZWQtbW9uc3Rlci03MS5jbGVyay5hY2NvdW50cy5kZXYk"
VITE_SENTRY_DSN = "https://a4abe058104d9e2142abe78f702e3de9@o4506190168522752.ingest.us.sentry.io/4508570874937344"

[env]
PORT = '8080'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
